using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using Editor.Dialog.Parser;

namespace Editor.Dialog.Emitter{
    /// Compiles a DialogScriptAst into deterministic, compile-safe C# Dialogue Graph script.
    public static class DialogCodeEmitter{
        /// Generates the complete C# code string representing the dialog graph.
        public static string Emit(DialogScriptAst ast, string targetNamespace = "Generated.Dialogues"){
            string className = $"{SanitizeIdentifier(ast.scriptName)}Dialogue";
            string fileSlug = SanitizeKeySlug(ast.scriptName);

            StringBuilder sb = new();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     This code was generated by the DialogBaker compiler.");
            sb.AppendLine($"//     Source: Assets/Dialogue/{ast.scriptName}.dialog");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Data;");
            sb.AppendLine("using Narrative.Blackboard;");
            sb.AppendLine("using Narrative.Dialog;");
            sb.AppendLine("using Tactical;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine($"namespace {targetNamespace}{{");
            sb.AppendLine($"    public class {className} : Dialogue{{");
            sb.AppendLine($"        public override string DialogueId => \"{ast.scriptName}\";");
            sb.AppendLine();

            // 1. Emit Blackboard Variable Proxies
            if (ast.variables.Count > 0){
                sb.AppendLine("        // Blackboard Variable Proxies");
                foreach (DialogVarDef varDef in ast.variables){
                    string csharpType = TranslateVariableType(varDef.typeName);
                    string defaultVal = TranslateDefaultValue(varDef.defaultValue, varDef.typeName);
                    string proxyType = varDef.scope switch {
                        "local" => $"DialogueVariable<{csharpType}>",
                        "map" => $"MapVariable<{csharpType}>",
                        "global" => $"GlobalVariable<{csharpType}>",
                        _ => $"DialogueVariable<{csharpType}>"
                    };

                    sb.AppendLine($"        public readonly {proxyType} {varDef.name} = new(\"{varDef.name}\", {defaultVal});");
                }
                sb.AppendLine();
            }

            // 2. Emit Constructor & Graph Assembly
            sb.AppendLine($"        public {className}(){{");
            sb.AppendLine("            BuildGraph();");
            sb.AppendLine("        }");
            sb.AppendLine();
            sb.AppendLine("        private void BuildGraph(){");
            foreach (DialogKnotDef knot in ast.knots){
                string methodName = $"BuildNode_{SanitizeIdentifier(knot.knotId)}";
                sb.AppendLine($"            AddNode(\"{knot.knotId}\", {methodName}());");
            }
            sb.AppendLine("        }");
            sb.AppendLine();

            // 3. Emit Node Builder Methods
            foreach (DialogKnotDef knot in ast.knots){
                EmitNodeMethod(sb, knot, fileSlug, ast);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// Generates an individual knot factory method.
        private static void EmitNodeMethod(StringBuilder sb, DialogKnotDef knot, string fileSlug, DialogScriptAst ast){
            string methodName = $"BuildNode_{SanitizeIdentifier(knot.knotId)}";
            string knotSlug = SanitizeKeySlug(knot.knotId);

            sb.AppendLine($"        private DialogueNode {methodName}(){{");
            sb.AppendLine("            return new DialogueNode{");
            sb.AppendLine($"                knotId = \"{knot.knotId}\",");
            sb.AppendLine($"                speakerId = \"{EscapeString(knot.speakerId)}\",");
            sb.AppendLine($"                portraitMood = \"{EscapeString(knot.portraitMood)}\",");

            if (!string.IsNullOrEmpty(knot.promptText))
                sb.AppendLine($"                textKey = \"DLG_{fileSlug}_{knotSlug}_PROMPT_00\",");

            if (knot.inLineCommands.Count > 0){
                sb.AppendLine("                onEnter = () => {");
                foreach (string cmd in knot.inLineCommands){
                    string translatedCmd = TranslateCommand(cmd, ast);
                    sb.AppendLine($"                    {translatedCmd}");
                }
                sb.AppendLine("                },");
            }

            if (knot.skillCheck != null){
                sb.AppendLine("                skillCheck = new DialogueSkillCheck{");
                sb.AppendLine($"                    skill = Skill.{knot.skillCheck.skill},");
                sb.AppendLine($"                    targetDc = {knot.skillCheck.targetDc},");

                EmitOutcome(sb, "onSuccess", knot.skillCheck.onSuccess, fileSlug, knotSlug, "SUCCESS", ast);
                EmitOutcome(sb, "onFailure", knot.skillCheck.onFailure, fileSlug, knotSlug, "FAILURE", ast);
                EmitOutcome(sb, "onCriticalSuccess", knot.skillCheck.onCriticalSuccess, fileSlug, knotSlug, "CRITICAL_SUCCESS", ast);
                EmitOutcome(sb, "onCriticalFailure", knot.skillCheck.onCriticalFailure, fileSlug, knotSlug, "CRITICAL_FAILURE", ast);

                sb.AppendLine("                },");
            }

            if (knot.problem != null){
                sb.AppendLine("                problem = new DialogueProblem{");
                sb.AppendLine($"                    archetypeId = \"{knot.problem.archetypeId}\",");
                sb.AppendLine($"                    baseLevel = {knot.problem.baseLevel},");

                EmitOutcome(sb, "onSuccess", knot.problem.onSuccess, fileSlug, knotSlug, "SUCCESS", ast);
                EmitOutcome(sb, "onFailure", knot.problem.onFailure, fileSlug, knotSlug, "FAILURE", ast);

                sb.AppendLine("                },");
            }

            if (knot.choices.Count > 0){
                sb.AppendLine("                choices = new List<DialogueChoice>{");
                for (int i = 0; i < knot.choices.Count; i++){
                    DialogChoiceDef choice = knot.choices[i];
                    sb.AppendLine("                    new DialogueChoice{");
                    sb.AppendLine($"                        choiceId = \"{choice.choiceId}\",");
                    sb.AppendLine($"                        textKey = \"DLG_{fileSlug}_{knotSlug}_CHOICE_{i:D2}\",");
                    sb.AppendLine($"                        isOneShot = {(choice.isOneShot ? "true" : "false")},");

                    if (choice.consumesAction)
                        sb.AppendLine("                        consumesAction = true,");
                    if (choice.endsTurn)
                        sb.AppendLine("                        endsTurn = true,");
                    if (choice.consumesMove)
                        sb.AppendLine("                        consumesMove = true,");

                    string visibilityExpr = BuildVisibilityExpression(choice, ast);
                    sb.AppendLine($"                        isVisible = () => {visibilityExpr},");

                    if (!string.IsNullOrEmpty(choice.requiredItemId)){
                        sb.AppendLine($"                        requiredItemId = \"{choice.requiredItemId}\",");
                        sb.AppendLine($"                        requiredItemAmount = {choice.requiredItemAmount},");
                    }

                    string target = choice.targetKnot == "END" ? "DialogueNode.End" : $"\"{choice.targetKnot}\"";
                    sb.AppendLine($"                        targetKnot = {target}");
                    sb.AppendLine("                    },");
                }
                sb.AppendLine("                }");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        /// Emits an outcome branch for a skill check or problem knot.
        private static void EmitOutcome(StringBuilder sb, string propertyName, DialogOutcomeDef outcome, string fileSlug, string knotSlug, string outcomeType, DialogScriptAst ast){
            if (outcome == null)
                return;

            sb.AppendLine($"                    {propertyName} = new DialogueOutcome{{");
            if (!string.IsNullOrEmpty(outcome.speakerId))
                sb.AppendLine($"                        speakerId = \"{EscapeString(outcome.speakerId)}\",");

            if (!string.IsNullOrEmpty(outcome.text))
                sb.AppendLine($"                        textKey = \"DLG_{fileSlug}_{knotSlug}_{outcomeType}_00\",");

            if (!string.IsNullOrEmpty(outcome.command)){
                string translatedCmd = TranslateCommand(outcome.command, ast);
                sb.AppendLine($"                        onExecute = () => {{ {translatedCmd} }},");
            }

            string target = outcome.targetKnot == "END" ? "DialogueNode.End" : $"\"{outcome.targetKnot}\"";
            sb.AppendLine($"                        targetKnot = {target}");
            sb.AppendLine("                    },");
        }

        /// Generates the C# lambda boolean expression governing choice visibility.
        private static string BuildVisibilityExpression(DialogChoiceDef choice, DialogScriptAst ast){
            StringBuilder expr = new();

            if (choice.isOneShot)
                expr.Append($"!IsChoiceConsumed(\"{choice.choiceId}\")");

            if (!string.IsNullOrEmpty(choice.condition)){
                string translatedCondition = TranslateCondition(choice.condition, ast);
                if (expr.Length > 0)
                    expr.Append(" && ");
                expr.Append($"({translatedCondition})");
            }

            return expr.Length == 0 ? "true" : expr.ToString();
        }

        /// Translates AST variable identifiers to C# Blackboard proxy accessors.
        private static string TranslateCondition(string rawCondition, DialogScriptAst ast){
            string result = rawCondition;
            foreach (DialogVarDef varDef in ast.variables){
                string replacement = varDef.scope switch {
                    "local" => $"{varDef.name}.Value",
                    "map" => $"Map.{varDef.name}.Value",
                    "global" => $"Session.{varDef.name}.Value",
                    _ => $"{varDef.name}.Value"
                };

                result = Regex.Replace(result, $@"\b{varDef.name}\b", replacement);
            }
            return result;
        }

        /// Translates an AST command string into executable C# expressions.
        private static string TranslateCommand(string command, DialogScriptAst ast){
            string trimmed = command.Trim();

            // EndCrisisTurn()
            if (trimmed.Equals("EndCrisisTurn()", StringComparison.OrdinalIgnoreCase))
                return "CrisisController.Instance?.EndPlayerTurn();";

            // DamagePlayer(amount)
            Match dmgMatch = Regex.Match(trimmed, @"^DamagePlayer\s*\(\s*([0-9]+)\s*\)$", RegexOptions.IgnoreCase);
            if (dmgMatch.Success)
                return $"DialogueController.Instance?.DamagePlayer({dmgMatch.Groups[1].Value});";

            // RewardItem(itemId, amount)
            Match rwdMatch = Regex.Match(trimmed, @"^RewardItem\s*\(\s*([a-zA-Z0-9_]+)\s*,\s*([0-9]+)\s*\)$", RegexOptions.IgnoreCase);
            if (rwdMatch.Success)
                return $"DialogueController.Instance?.RewardItem(\"{rwdMatch.Groups[1].Value}\", {rwdMatch.Groups[2].Value});";

            // SET VariableName = Value
            Match setMatch = Regex.Match(trimmed, @"^SET\s+([a-zA-Z_][a-zA-Z0-9_]*)\s*=\s*(.+)$", RegexOptions.IgnoreCase);
            if (setMatch.Success){
                string varName = setMatch.Groups[1].Value;
                string rawValue = setMatch.Groups[2].Value.Trim();

                foreach (DialogVarDef varDef in ast.variables){
                    if (varDef.name == varName){
                        string val = TranslateValue(rawValue, varDef.typeName);
                        return $"{varName}.Value = {val};";
                    }
                }
            }

            return $"// Unrecognized command: {command}";
        }

        private static string TranslateVariableType(string typeName) => typeName.ToLowerInvariant() switch {
            "bool" => "bool",
            "int" => "int",
            "float" => "float",
            "string" => "string",
            _ => "string"
        };

        private static string TranslateDefaultValue(string defaultValue, string typeName) => typeName.ToLowerInvariant() switch {
            "bool" => defaultValue.ToLowerInvariant() == "true" ? "true" : "false",
            "int" => int.TryParse(defaultValue, out int i) ? i.ToString() : "0",
            "float" => float.TryParse(defaultValue, out float f) ? $"{f}f" : "0f",
            "string" => $"\"{EscapeString(defaultValue.Trim('\"'))}\"",
            _ => $"\"{EscapeString(defaultValue)}\""
        };

        private static string TranslateValue(string val, string typeName) => typeName.ToLowerInvariant() switch {
            "bool" => val.ToLowerInvariant() == "true" ? "true" : "false",
            "int" => int.TryParse(val, out int i) ? i.ToString() : "0",
            "float" => float.TryParse(val, out float f) ? $"{f}f" : "0f",
            "string" => $"\"{EscapeString(val.Trim('\"'))}\"",
            _ => $"\"{EscapeString(val)}\""
        };

        private static string SanitizeIdentifier(string name){
            if (string.IsNullOrEmpty(name)) return "Unnamed";
            StringBuilder sb = new();
            foreach (char c in name){
                if (char.IsLetterOrDigit(c) || c == '_')
                    sb.Append(c);
            }
            return sb.Length == 0 ? "Unnamed" : sb.ToString();
        }

        private static string SanitizeKeySlug(string name){
            if (string.IsNullOrEmpty(name)) return "EMPTY";
            StringBuilder sb = new();
            foreach (char c in name){
                if (char.IsLetterOrDigit(c))
                    sb.Append(char.ToUpperInvariant(c));
                else if (c == '_')
                    sb.Append('_');
            }
            return sb.Length == 0 ? "UNKNOWN" : sb.ToString();
        }

        private static string EscapeString(string str) =>
            str.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "");
    }
}
