using System;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using Editor.Dialog.Parser;

namespace Editor.Dialog.Emitter{
    /// Generates strongly-typed C# classes inheriting from DialogueBehaviour for parsed DialogScriptAst trees.
    /// Strictly avoids string evaluation at runtime by emitting native C# delegates and compiled lambdas.
    public static class DialogCodeEmitter{
        private const string DefaultGeneratedScriptsFolder = "Assets/Scripts/Generated/Dialogues";

        /// Emits the C# class for the given AST.
        /// Returns the path of the written file.
        public static string Emit(DialogScriptAst ast, string targetDirectory = null){
            string folder = string.IsNullOrEmpty(targetDirectory) ? DefaultGeneratedScriptsFolder : targetDirectory;
            if (!Directory.Exists(folder))
                Directory.CreateDirectory(folder);

            string className = $"{SanitizeIdentifier(ast.scriptName)}Dialogue";
            string fullPath = Path.Combine(folder, $"{className}.cs");

            StringBuilder sb = new();
            string fileSlug = SanitizeKeySlug(ast.scriptName);

            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine($"//     Generated by Hollow Signal Dialog Baker from: {ast.scriptName}.dialog");
            sb.AppendLine("//     DO NOT EDIT DIRECTLY. Changes will be overwritten upon re-baking.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine();
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using Core;");
            sb.AppendLine("using Core.Dialog;");
            sb.AppendLine("using Data;");
            sb.AppendLine("using Generated.Maps;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Generated.Dialogues{");
            sb.AppendLine("    /// Auto-generated dialogue state machine.");
            sb.AppendLine("    [DisallowMultipleComponent]");
            sb.AppendLine($"    public class {className} : DialogueBehaviour{{");

            // 1. Local Tracked<T> Variables
            bool hasLocalVars = false;
            foreach (DialogVarDef varDef in ast.variables){
                if (varDef.scope == "local"){
                    if (!hasLocalVars){
                        sb.AppendLine("        [Header(\"Tracked Variables (Local Instance)\")]");
                        hasLocalVars = true;
                    }
                    string csType = NormalizeType(varDef.typeName);
                    string defaultVal = FormatDefaultValue(varDef.typeName, varDef.defaultValue);
                    sb.AppendLine($"        public Tracked<{csType}> {varDef.name} = new(\"{varDef.name}\", {defaultVal});");
                }
            }

            if (hasLocalVars)
                sb.AppendLine();

            // 2. Strongly-typed or concrete Map Proxy accessor helper
            string mapCastType = !string.IsNullOrEmpty(ast.mapName) ? $"{SanitizeIdentifier(ast.mapName)}Variables" : "MapDialogVariables";
            sb.AppendLine($"        private static {mapCastType} Map => ({mapCastType})MapDialogVariables.Instance;");
            sb.AppendLine($"        private static SessionDialogVariables Session => SessionDialogVariables.Instance;");
            sb.AppendLine();

            // 3. GetNode Dispatcher
            sb.AppendLine("        /// Resolves knot by ID and builds the corresponding DialogueNode.");
            sb.AppendLine("        public override DialogueNode GetNode(string knotId) => knotId switch {");
            foreach (DialogKnotDef knot in ast.knots){
                string methodName = $"BuildNode_{SanitizeIdentifier(knot.knotId)}";
                sb.AppendLine($"            \"{knot.knotId}\" => {methodName}(),");
            }
            sb.AppendLine("            _ => null");
            sb.AppendLine("        };");
            sb.AppendLine();

            // 4. Knot Builder Methods
            foreach (DialogKnotDef knot in ast.knots){
                EmitKnotMethod(sb, knot, fileSlug, ast);
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            File.WriteAllText(fullPath, sb.ToString(), Encoding.UTF8);
            return fullPath;
        }

        private static void EmitKnotMethod(StringBuilder sb, DialogKnotDef knot, string fileSlug, DialogScriptAst ast){
            string knotSlug = SanitizeKeySlug(knot.knotId);
            string methodName = $"BuildNode_{SanitizeIdentifier(knot.knotId)}";

            sb.AppendLine($"        private DialogueNode {methodName}(){{");
            sb.AppendLine("            return new DialogueNode{");
            sb.AppendLine($"                knotId = \"{knot.knotId}\",");
            sb.AppendLine($"                speakerId = \"{EscapeString(knot.speakerId)}\",");
            sb.AppendLine($"                portraitMood = \"{EscapeString(knot.portraitMood)}\",");

            if (!string.IsNullOrEmpty(knot.promptText)){
                sb.AppendLine($"                textKey = \"DLG_{fileSlug}_{knotSlug}_PROMPT_00\",");
            }

            // OnEnter commands
            if (knot.inLineCommands.Count > 0){
                sb.AppendLine("                onEnter = () => {");
                foreach (string cmd in knot.inLineCommands){
                    string translatedCmd = TranslateCommand(cmd, ast);
                    sb.AppendLine($"                    {translatedCmd}");
                }
                sb.AppendLine("                },");
            }

            // Skill Check
            if (knot.skillCheck != null){
                sb.AppendLine("                skillCheck = new DialogueSkillCheck{");
                sb.AppendLine($"                    skill = Skill.{knot.skillCheck.skill},");
                sb.AppendLine($"                    targetDc = {knot.skillCheck.targetDc},");

                EmitOutcome(sb, "onSuccess", knot.skillCheck.onSuccess, fileSlug, knotSlug, "SUCCESS", ast);
                EmitOutcome(sb, "onFailure", knot.skillCheck.onFailure, fileSlug, knotSlug, "FAILURE", ast);
                EmitOutcome(sb, "onCriticalSuccess", knot.skillCheck.onCriticalSuccess, fileSlug, knotSlug, "CRITICAL_SUCCESS", ast);
                EmitOutcome(sb, "onCriticalFailure", knot.skillCheck.onCriticalFailure, fileSlug, knotSlug, "CRITICAL_FAILURE", ast);

                sb.AppendLine("                },");
            }

            // Choices
            if (knot.choices.Count > 0){
                sb.AppendLine("                choices = new List<DialogueChoice>{");
                for (int i = 0; i < knot.choices.Count; i++){
                    DialogChoiceDef choice = knot.choices[i];
                    sb.AppendLine("                    new DialogueChoice{");
                    sb.AppendLine($"                        choiceId = \"{choice.choiceId}\",");
                    sb.AppendLine($"                        textKey = \"DLG_{fileSlug}_{knotSlug}_CHOICE_{i:D2}\",");
                    sb.AppendLine($"                        isOneShot = {(choice.isOneShot ? "true" : "false")},");

                    // Visibility Lambda
                    string visibilityExpr = BuildVisibilityExpression(choice, ast);
                    sb.AppendLine($"                        isVisible = () => {visibilityExpr},");

                    // Required Item Gating
                    if (!string.IsNullOrEmpty(choice.requiredItemId)){
                        sb.AppendLine($"                        requiredItemId = \"{choice.requiredItemId}\",");
                        sb.AppendLine($"                        requiredItemAmount = {choice.requiredItemAmount},");
                    }

                    // Target Knot
                    string target = choice.targetKnot == "END" ? "DialogueNode.End" : $"\"{choice.targetKnot}\"";
                    sb.AppendLine($"                        targetKnot = {target}");
                    sb.AppendLine("                    },");
                }
                sb.AppendLine("                }");
            }

            sb.AppendLine("            };");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        private static void EmitOutcome(StringBuilder sb, string propertyName, DialogOutcomeDef outcome, string fileSlug, string knotSlug, string outcomeType, DialogScriptAst ast){
            if (outcome == null) return;

            sb.AppendLine($"                    {propertyName} = new DialogueOutcome{{");
            sb.AppendLine($"                        speakerId = \"{EscapeString(outcome.speakerId)}\",");
            sb.AppendLine($"                        textKey = \"DLG_{fileSlug}_{knotSlug}_{outcomeType}_00\",");

            if (!string.IsNullOrEmpty(outcome.command)){
                string translatedCmd = TranslateCommand(outcome.command, ast);
                sb.AppendLine($"                        onExecute = () => {{ {translatedCmd} }},");
            }

            string target = outcome.targetKnot == "END" ? "DialogueNode.End" : $"\"{outcome.targetKnot}\"";
            sb.AppendLine($"                        targetKnot = {target}");
            sb.AppendLine("                    },");
        }

        private static string BuildVisibilityExpression(DialogChoiceDef choice, DialogScriptAst ast){
            StringBuilder expr = new();

            if (choice.isOneShot){
                expr.Append($"!IsChoiceConsumed(\"{choice.choiceId}\")");
            }

            if (!string.IsNullOrEmpty(choice.condition)){
                string translatedCondition = TranslateCondition(choice.condition, ast);
                if (expr.Length > 0)
                    expr.Append(" && ");
                expr.Append($"({translatedCondition})");
            }

            if (expr.Length == 0)
                return "true";

            return expr.ToString();
        }

        private static string TranslateCondition(string rawCondition, DialogScriptAst ast){
            string result = rawCondition;
            foreach (DialogVarDef varDef in ast.variables){
                string replacement = varDef.scope switch {
                    "local" => $"{varDef.name}.Value",
                    "map" => $"Map.{varDef.name}.Value",
                    "global" => $"Session.{varDef.name}.Value",
                    _ => $"{varDef.name}.Value"
                };

                result = Regex.Replace(result, $@"\b{varDef.name}\b", replacement);
            }
            return result;
        }

        private static string TranslateCommand(string rawCmd, DialogScriptAst ast){
            if (!rawCmd.StartsWith("SET ", StringComparison.OrdinalIgnoreCase))
                return $"{rawCmd}();";

            string assignment = rawCmd.Substring(4).Trim();
            int eqIdx = assignment.IndexOf('=');
            if (eqIdx <= 0)
                return $"{assignment};";

            string varName = assignment.Substring(0, eqIdx).Trim();
            string expression = assignment.Substring(eqIdx + 1).Trim();

            DialogVarDef foundVar = ast.variables.Find(v => v.name == varName);
            if (foundVar != null){
                return foundVar.scope switch {
                    "local" => $"{varName}.Value = {expression};",
                    "map" => $"Map.{varName}.Value = {expression};",
                    "global" => $"Session.{varName}.Value = {expression};",
                    _ => $"{varName}.Value = {expression};"
                };
            }

            return $"{assignment};";
        }

        private static string NormalizeType(string typeName) => typeName switch{
            "bool" => "bool",
            "int" => "int",
            "float" => "float",
            "string" => "string",
            _ => typeName
        };

        private static string FormatDefaultValue(string typeName, string rawDefault){
            if (string.IsNullOrEmpty(rawDefault))
                return typeName == "string" ? "\"\"" : "default";
            if (typeName == "string" && !rawDefault.StartsWith("\""))
                return $"\"{rawDefault}\"";
            if (typeName == "float" && !rawDefault.EndsWith("f", StringComparison.OrdinalIgnoreCase))
                return $"{rawDefault}f";
            return rawDefault;
        }

        private static string SanitizeIdentifier(string raw){
            if (string.IsNullOrEmpty(raw)) return "Script";
            return raw.Replace(" ", "_").Replace("-", "_");
        }

        private static string SanitizeKeySlug(string raw){
            if (string.IsNullOrEmpty(raw)) return "KEY";
            return raw.ToUpperInvariant().Replace(" ", "_").Replace("-", "_");
        }

        private static string EscapeString(string raw){
            if (string.IsNullOrEmpty(raw)) return string.Empty;
            return raw.Replace("\"", "\\\"");
        }
    }
}
