import csv

# Consolidated 83 distinct skills without redundant duplicates
data = [
    # Demolitions & Chemistry
    ("Incendiaries", "Arcane-Mental", "Formulate, refine, and stabilize flammable petrochemical fuels, jellied accelerants, and volatile vapor mixtures.", "Focuses strictly on creating and optimizing liquid fires and napalm; differs from Explosives (shockwaves and brisance) and Chemistry (general preparation)."),
    ("Explosives", "Arcane-Mental", "Synthesize and calibrate sensitive secondary explosive compounds, blasting caps, and high-velocity detonation pastes.", "Deals with shockwaves and shattering force; distinct from Incendiaries (burning/heat) and Bombcraft (casing and physical packaging)."),
    ("Bombcraft", "Mechanical", "Assemble, pack, and shape physical charges, directional blast cones, and kinetic casing fragmentation.", "Governs the physical architecture of the explosive shell or shape charge; distinct from Explosives (the chemical paste) and Fuses (the trigger mechanism)."),
    ("Fuses", "Mechanical", "Design, wire, and troubleshoot clockwork fuses, friction primers, impact triggers, and trip-cords.", "Focuses exclusively on trigger mechanisms and delays; distinct from Bombcraft (the payload itself) and Trapping (non-explosive snare/tethers)."),
    ("Poisons", "Arcane-Mental", "Extract, distill, and preserve bio-toxins, animal venoms, irradiated plant pulps, and nervous system agents.", "Pertains to biological toxins affecting living organisms; distinct from Acids (which dissolve metal, rubber, and armor) and Incendiaries."),
    ("Acids", "Arcane-Mental", "Brew, distill, and neutralize concentrated acids, stripping agents, and rust-eating alkali solutions.", "Targets inanimate surfaces, vehicle chassis, and armor plates; distinct from Poisons (targets biology) and Incendiaries (targets flammability)."),
    ("Trapping", "Mechanical", "Fabricate, calibrate, and balance tensioned wire snares, spring-loaded caltrops, spiked tire-shredders, and kinetic entanglement devices.", "Covers physical kinetic containment and tire puncture devices; distinct from Fuses (blast primers) and Rigging (modifying vehicle frames)."),
    ("Scavenging", "Arcane-Mental", "Assess roadside junk, scrap piles, and abandoned wrecks to identify chemically active residues, high-grade alloys, and usable bomb components.", "Assessing viability and latent value of materials in the wasteland; distinct from Chemistry (processing) and Bombcraft (building)."),
    ("Chemistry", "Arcane-Mental", "Perform tabletop bench-work, improvised crystallization, filtration, and boiling with crude desert apparatus and salvaged glassware.", "General lab process and equipment safety on the road; distinct from specific chemical outputs like Incendiaries or Acids."),
    ("Demolition", "Arcane-Mental", "Calculate load-bearing weak points, shear angles, and minimum charge weights to collapse bridges, canyon chokepoints, or vehicle axles.", "Diagnostic engineering knowledge of where to place explosives for structural collapse; distinct from Bombcraft (the device itself)."),
    ("Defusing", "Mechanical", "Trace foreign circuitry, identify booby-trap triggers, snip tensioned tripwires, and render rival ordnance inert under pressure.", "Reverse engineering and disabling enemy traps; distinct from Fuses (arming your own) and Demolition (blowing things up)."),
    ("Pyrotechnics", "Covert", "Compound and deploy color-coded flares, blinding flash-bombs, smoke curtains, and acoustic disorientation noisemakers.", "Non-lethal sensory denial and obscuration; distinct from Incendiaries (killing fire) and Explosives (kinetic damage)."),
    ("Hazard Control", "Arcane-Mental", "Neutralize rogue spills, dampen thermal runaway, ventilate toxic drafts, and stabilize ticking, half-cooked payloads.", "Emergency containment of chemical and explosive mishaps; distinct from Chemistry (planned synthesis)."),
    ("Blast Geometry", "Arcane-Mental", "Mentally calculate shockwave dispersion, fragmentation arcs, and shrapnel ricochets around metal car chassis and open highway terrain.", "Predictive geometry of blast aftermath to protect allies and shred pursuers; distinct from Throwing (lobbing) and Demolition (structures)."),
    ("Lubrication", "Arcane-Mental", "Formulate slippery surface coatings, heat-resistant bearing greases, and anti-friction treatments to slip free from grabs or protect machinery.", "Chemical lubrication and friction reduction; distinct from destructive Acids and fuel Siphoning."),
    ("Rad Cleansing", "Arcane-Mental", "Filter irradiated water, identify hot fallout pockets along the highway, and brew chelating rinses to flush radiation sickness.", "Managing nuclear contamination and radiation poisoning; distinct from Hazard Control (blast/spill safety) and Chemistry."),
    ("Provisions", "Arcane-Mental", "Preserve spoiled meats, purify rancid roadkill with saltpeter, render animal fat into glycerin (useful for soap or nitroglycerin), and brew potable moonshine.", "Domestic food survival crossing over into explosive precursor production; distinct from Incendiaries or Chemistry."),

    # Driving & Vehicle Dynamics
    ("Drift", "Physical", "Manipulate weight transfer, handbrake friction, and throttle slip to slide heavy multi-ton vehicles through corners without losing momentum or rolling.", "Governs controlled loss of traction and lateral momentum; distinct from Pursuit (racing lines) and Offroading (terrain reading)."),
    ("Ramming", "Physical", "Judge impact vectors, bumper angles, and crumple zones to deliver bone-crushing vehicular hits against targets while protecting his own steering and radiator.", "The tactical art of offensive vehicular collision; distinct from Fending (rubbing/deflecting hits) and Heavy Hauling (towing)."),
    ("Fending", "Physical", "Counter-steer, shoulder, and rub fenders against flanking raiders to grind bikes into dust or deflect PIT maneuvers without spinning out.", "Defensive contact driving against adjacent pursuers trying to force him off-road; distinct from Ramming (high-impact front/T-bone hits)."),
    ("Offroading", "Physical", "Read dunes, washouts, scree slopes, and salt flats at speed to choose the line that won't bottom out the chassis, high-center, or flip the truck.", "Environmental surface reading and handling unpredictable ground; distinct from Highway Lore (map/route navigation) and Drift (cornering slip)."),
    ("Heavy Hauling", "Mechanical", "Gauge tongue weight, axle load limits, tow hitch strain, and trailer sway under brutal crosswinds and erratic emergency turns.", "Knowledge of towing trailers, tankers, and multi-wheeled rigs; distinct from Pursuit (general driving lines) and Brawn (brute force)."),
    ("Pursuit", "Physical", "Calculate intercept vectors, draft behind vehicle wakes, cut racing lines, and block passing lanes against faster, lighter adversaries.", "High-speed competitive chase geometry and line selection; distinct from Ramming (striking) and Offroading (terrain reading)."),
    ("Vehicle Weight", "Arcane-Mental", "Intuit the shifting center of gravity, cargo slosh, and suspension roll of loaded trucks to avoid rollover during violent maneuvers.", "Instinctive physics-based spatial awareness of mass in motion; distinct from Heavy Hauling (tow rigging) and Brawn (muscle)."),
    ("Stunt Recovery", "Physical", "Bring vehicles down safely from airborne jumps, regain steering after two-wheeling, and recover control out of flat-spins.", "Crisis recovery from catastrophic vehicular instability; distinct from planned maneuvers like Drift or standard Offroading."),
    ("Engine Listening", "Arcane-Mental", "Diagnose failing head gaskets, pinging cylinders, slipping belts, and dry bearings purely from audio pitch, engine hum, and chassis tremors.", "Sensory diagnosis through hearing and vibration; distinct from Mechanics (fixing it) and enemy vehicle diagnosis."),
    ("Highway Lore", "Arcane-Mental", "Recall ruined interstate numbers, collapsed cloverleafs, fuel pipeline routes, canyon pinch-points, and passable asphalt strips across the wastes.", "Roadway navigation, landmarks, and route planning; distinct from tactical driving (Offroading) and enemy psychology (Raider Lore)."),
    ("Convoy Tactics", "Arcane-Mental", "Maintain defensive formations, shepherd vulnerable companion cars, coordinate vehicle screens, and block raiders from isolating allies.", "Multi-vehicle group strategy and escort driving; distinct from solo pursuit maneuvers (Pursuit) or individual aggression (Fending)."),
    ("Tire Sense", "Arcane-Mental", "Gauge remaining rubber tread, detect slow leaks from road heat, and estimate how much punishment worn tires can endure before a fatal blowout.", "Hyper-focused awareness of tire condition, pressure, and blow-out risk under wasteland heat; distinct from offensive tire destruction (Trapping)."),
    ("Vehicle Flaws", "Mechanical", "Diagnose critical mechanical vulnerabilities (exposed fuel lines, weak steering knuckles, dry differentials) on pursuing raider buggies at a glance.", "Spotting mechanical structural weaknesses on enemy vehicles; distinct from Rigging (modifying own car) and Demolition (static bridges)."),
    ("Lashing", "Mechanical", "Secure erratic heavy payloads, fuel drums, and loose ammunition crates with ratchet straps, chains, and trucker hitches to withstand violent rollover angles.", "Physical load restraint and freight security; distinct from Vehicle Weight (feeling cargo shift while driving) and Rigging (mounting weapons)."),
    ("Siphoning", "Covert", "Rapidly tap fuel tanks, prime manual hoses without swallowing poison sludge, and salvage usable unrefined petrol from burning wrecks.", "Opportunistic fuel harvesting and fluid transfer under time limits; distinct from Scavenging (scrap/parts) and Incendiaries (fuel synthesis)."),
    ("Hotwiring", "Mechanical", "Bypass ruined ignition tumblers, splice starter wires, and bridge solenoid relays to commandeer raider vehicles under fire.", "Rapid illicit vehicle ignition and commandeering; distinct from Mechanics (engine overhaul) and Fuses (detonators)."),

    # Mechanics, Engineering & Systems
    ("Mechanics", "Mechanical", "Service, tune, overhaul, and synchronize carburetors, pistons, timing belts, and superchargers to keep high-stress wasteland engines running.", "Deep mechanical knowledge of internal combustion blocks and drive components; distinct from Automata (robotics/computers) and Rigging (chassis mounts)."),
    ("Rigging", "Mechanical", "Clamp, strap, route blast shields, and mount deployable trap dispensers or drop chutes onto vehicle frames.", "Interface between traps/chutes and the vehicle hull; distinct from driving/piloting or internal engine mechanics."),
    ("Machining", "Mechanical", "Grind, mill, bore, and fabricate replacement gears, bespoke bushings, and metal adapters from loose junk using portable scrap lathes and files.", "The manufacturing and shaping of precise mechanical components; distinct from Metallurgy (heat treatment/blast resistance) and Mechanics (assembly/tuning)."),
    ("Metallurgy", "Mechanical", "Anneal, temper, and cold-forge recovered scrap metal, engine blocks, and pipe casings to withstand explosive chamber pressures without rupturing prematurely.", "Knowing stress tolerances, brittleness, and heat limits of junk metals; distinct from Scavenging (finding scrap) and Bombcraft (shaping payloads)."),
    ("Overclocking", "Mechanical", "Bypass governor limits, reroute coolants, and force superchargers or hydraulic valves past manufacturer tolerances for critical bursts of speed or power.", "Pushing systems beyond safe operational limits; distinct from standard Mechanics tuning and Hazard Control (stopping failures)."),
    ("Mid-Drive Repair", "Mechanical", "Clamber onto exposed hoods, wheel wells, and undercarriages at 80 mph to crimp blown lines, extinguish radiator fires, and swap belts mid-flight.", "Real-time mechanical triage under extreme kinetic motion and wind; distinct from Mechanics (calm workshop repair) and Parkour (pure athletic movement)."),
    ("Pneumatics", "Mechanical", "Trace, pressure-test, seal, and route compressed air lines, pneumatic pistons, air horns, and pressurized braking systems.", "Fluid power via compressed gases; distinct from Hydraulics (liquid pressure) and Mechanics."),
    ("Hydraulics", "Mechanical", "Balance reservoir pressure, repack seals, and plumb high-pressure fluid lines for steering assist, suspension lifts, and hydraulic rams.", "Fluid power via uncompressible oils/liquids; distinct from Pneumatics (gas pressure) and Mechanics."),
    ("Wiring", "Mechanical", "Trace multi-strand automotive looms, solder frayed leads, eliminate short circuits, and isolate dead relays in vibrating vehicle hulls.", "Heavy DC automotive electrical systems; distinct from Automata (micro-logic chips/robotics) and Hotwiring (ignition bypass)."),
    ("Sabotage", "Mechanical", "Sever brake fluid lines, drop dirt in fuel caps, unpin steering linkages, and loosen lug nuts on enemy vehicles during boarding runs.", "The stealthy, intentional crippling of enemy mechanical assemblies; distinct from Mid-Drive Repair (fixing friendly cars) and Smashing (violent brute destruction)."),
    ("Battery Tech", "Mechanical", "Recondition lead-acid cells, scavenge lithium packs, wire series/parallel banks, and jump dead systems using electrostatic shocks.", "DC electrical energy storage and chemical power cells; distinct from vehicle Wiring and Overclocking."),
    ("Chassis Maintenance", "Mechanical", "Weld cracked armor plating, replace stripped hydraulic gaskets, replenish coolant loops, and clear debris from armored exoskeletons or bodies.", "Self-servicing of armored suits, frames, and bodies; distinct from Mechanics (vehicle motors) and Automata (software logic)."),
    ("Prosthetics", "Mechanical", "Fit, calibrate, suture, and interface mechanical limb replacements, robotic braces, and bone splints onto organic skeletons.", "The fusion of living biology with mechanics; distinct from Surgery (pure biological repair) and Chassis Maintenance (self-repair)."),

    # Robotics, Cybernetics & Pre-War Tech
    ("Automata", "Arcane-Mental", "Read circuit boards, interpret logic gates, interface with robotic relays, and diagnose autonomous machine behavior learned from pre-war machines.", "Focuses on cybernetic/robotic logic and silicon circuits; distinct from Mechanics (greasy mechanical motors) and Machine Link (direct datalinks)."),
    ("Machine Link", "Arcane-Mental", "Jack physical optical cables and radio datalinks directly into enemy drones, automated turrets, or security terminals to read memory banks and seize telemetry.", "Hardware-level data transfer and automated network interfacing; distinct from Wiring and Automata."),
    ("Electronic Countermeasures", "Covert", "Broadcast high-power static noise, flood radio frequencies, and scramble raider walkie-talkies or remote detonator signals using onboard transmitters.", "Signal jamming and electronic warfare; distinct from physical Machine Link and visual Pyrotechnics."),
    ("Thermal Dampening", "Covert", "Divert heat exhaust into specialized heat sinks, suppress engine IR signatures, and mask thermal bloom from night-vision sensors.", "Active IR cloaking and heat profile management; distinct from passive Thermal Sense and Hazard Control."),
    ("Pre-War Lore", "Arcane-Mental", "Query historical archives and memories to identify corporate bunker coordinates, classified weapon caches, orbital satellite schedules, and pre-collapse history.", "Historical and military pre-apocalypse database retrieval; distinct from practical Highway Lore and tribal Raider Lore."),

    # Combat, Weapons & Physicality
    ("Shotguns", "Physical", "Rapidly load, index shot patterns, control heavy recoil, and maintain break-action or pump-action scatterguns.", "Handling, spread estimation, and recoil control of wide-bore firearms; distinct from Handloading (crafting shells) and Footing (balance on moving car)."),
    ("Handloading", "Mechanical", "Hand-load, pack, and crimp bespoke shotgun shells (slugs, dragon's breath, flea-shrapnel, chem-vials, rock-salt).", "Crafting and customizing the cartridge itself; distinct from Shotguns (firing the gun) and Incendiaries (producing the powder)."),
    ("Pistols", "Physical", "Align sights, correct lead, and fire one-handed with sidearms while steering with the other hand amidst cabin vibration and recoil.", "One-handed weapon proficiency tailored to drive-by shooting; distinct from two-handed Shotguns or rifle marksmanship."),
    ("Submachine Guns", "Physical", "Manage cyclic fire rates, sweep close-to-mid range kill zones, and control rapid-fire muzzle climb on pistol-caliber automatic weapons.", "Tactical handling of high-rate-of-fire compact automatics; distinct from Assault Rifles (longer range/caliber) and Pistols."),
    ("Assault Rifles", "Physical", "Index bursts, compensate for bullet drop, transition between semi- and full-auto, and lay down disciplined suppressive fire at medium ranges.", "Mastery of standard infantry service rifles; distinct from Submachine Guns (CQB fire) and wide-bore Shotguns."),
    ("Slings", "Physical", "Whirl and whip ball bearings, spark plugs, rusted bolts, and acid vials with deadly velocity using leather straps and surgical tubing.", "Improvised mechanical projectile delivery; distinct from manual Throwing and firearms like Pistols."),
    ("Throwing", "Physical", "Lob grenades, pots, and canisters accurately while compensating for oncoming headwind, chassis bounce, and vehicle momentum.", "Manual lobbing trajectory under highway wind and vehicle speed; distinct from Fuses (priming triggers) and Shotguns."),
    ("Bludgeons", "Physical", "Swing tire irons, lead pipes, breaker bars, and heavy wrenches with devastating blunt kinetic momentum in melee reach.", "Mastery of heavy, unyielding blunt melee weapons; distinct from Grappling (unarmed holds) and Smashing (bashing objects)."),
    ("Blades", "Physical", "Wield high-frequency surgical scalpels, combat knives, and bone-saws with micro-millimeter precision against enemy joints and exposed tendons in melee.", "Ultra-precise cutting with edged weapons in close combat; distinct from feral Biting and blunt Bludgeons."),
    ("Biting", "Physical", "Target nerve clusters, fingers, wrists, and soft cartilage with vicious, locking jaw strength when pinned or grabbed by enemies.", "Feral close-quarters unarmed desperation defense; distinct from wrestling Grappling and passive Elusion."),
    ("Grappling", "Physical", "Choke, toss, headbutt, and bearhug boarders who breach the cab or climb into the driver's side window.", "Unarmed close-quarters fighting in cramped driver cabin spaces; distinct from Brawn (general lifting/prying) and Pistols."),
    ("Clamping", "Physical", "Lock motorized or vice-like grips into non-releasing clamps around raider weapons, steering rims, boarding ladders, or enemy wrists.", "Mechanical or vice-like clamping torque that cannot tire or slip; distinct from muscle Brawn and whole-body Ballistic Bracing."),
    ("Boarder Defense", "Physical", "Dislodge grappling hooks, boot clambering raiders off running boards, and leverage prybars and gun-butts in cramped chassis quarters.", "CQC defense on vehicle platforms and running boards; distinct from Footing (passive balance) and Shotguns (firearms)."),
    ("Smashing", "Physical", "Direct concentrated bodily mass and blunt instruments into structural failure points to smash engine blocks, shatter door hinges, and crush seized components.", "Deliberate physical destruction of objects and machinery through brute impact; distinct from Brawn (lifting/holding) and Demolition (explosives)."),
    ("Breaching", "Physical", "Leverage shoulder checks, prybars, and raw body torque to breach barricaded garage gates, clear rusted scrap piles, and bust through road obstacles.", "Applying bodily mass to clear environmental blockades and heavy doors; distinct from Smashing (destroying discrete items) and Ramming (using the car)."),
    ("Brawn", "Physical", "Apply raw muscular leverage to wrestle unassisted steering columns, pry crushed doors open, unstick seized trailer hitches, and manhandle cargo.", "Pure bodily strength and brute force; distinct from technical vehicle systems and combat techniques like Grappling."),
    ("Footing", "Physical", "Lock footing, absorb sway, and maintain dynamic balance while working or aiming on high-speed, violently swaying chassis.", "Dynamic bodily equilibrium under high vehicular G-forces; distinct from general athletic balance or weapon aiming."),
    ("Ballistic Bracing", "Physical", "Lock skeletal joints or anchor heavy mass into vehicle frames to eliminate weapon recoil and absorb oncoming ram impacts.", "Using structural weight and bracing to resist kinetic shock; distinct from organic Footing and muscle Brawn."),
    ("Shielding", "Physical", "Position dense, armored bodily mass or handheld plates between high-caliber bullets, shrapnel sprays, or flying debris to protect allies.", "Using bodily mass as passive cover; distinct from Ballistic Bracing (locking down to shoot) and evasive Elusion."),
    ("Fire Control", "Arcane-Mental", "Calculate lead angles, windage vectors, relative target velocity, and trajectory arcs using precision targeting mathematics.", "Predictive ballistics and targeting calculation; distinct from manual Assault Rifles handling or calculated Blast Geometry."),

    # Agility, Stealth & Awareness
    ("Parkour", "Physical", "Vault across roll cages, scramble up antenna masts, swing from roof racks, and scale sheer terrain using nimble, four-limbed momentum.", "Dynamic full-body climbing and traversal; distinct from Squeezing (static tight gaps) and Footing (bracing heavy feet on a floor)."),
    ("Squeezing", "Physical", "Contort joints, compress limbs, and thread a tiny or flexible frame through engine bays, ventilation ducts, frame gaps, and crawlspaces.", "Navigating tight structural bottlenecks and micro-apertures; distinct from Parkour (open leaping and climbing) and Stealth (not being seen)."),
    ("Stealth", "Covert", "Blend into shadows under truck beds, match vibrations to engine noise, and move soundlessly across loose gravel and sheet metal.", "Avoiding detection by sight and hearing; distinct from Squeezing (fitting into tight spaces) and Elusion (active defensive evasion)."),
    ("Elusion", "Physical", "Read hostile reach, slip out of grapple attempts, drop under swinging melee weapons, and dodge point-blank projectiles through sheer reflexes.", "Active personal combat evasion and ducking; distinct from Parkour (terrain traversal) and Grappling (grabbing back)."),
    ("Lockpicking", "Covert", "Rake wafers, tension rusted tumblers, and pop padlocks and ignition locks using thin scrap shims and wire needles.", "Manipulating keyed mechanical locking mechanisms; distinct from Hotwiring (electrical bypass) and Breaching (breaking down doors)."),
    ("Concealment", "Covert", "Disguise high-grade detonators, secret vials, and blasting powder in innocuous domestic knickknacks (tea tins, knitting bags, thermos flasks).", "Hiding and insulating volatile contraband in domestic containers; distinct from Hazard Control (stopping leaks) and Trapping."),
    ("Feral Instinct", "Arcane-Mental", "Sense imminent ambushes, structural collapse, predator presence, and mechanical explosions moments before they happen via hair-trigger sensory acuity.", "Sixth-sense primal danger awareness and intuition; distinct from Engine Listening (sound diagnosis) or calculated Blast Geometry."),
    ("Thermal Sense", "Arcane-Mental", "Read subtle radiant heat signatures, manifold glows, cooling fluid gradients, and hot engine pockets through heightened sensitivity.", "Organic thermal diagnostics and darkness navigation; distinct from audio-based Engine Listening and Hazard Control."),
    ("Weather Sense", "Arcane-Mental", "Spot dust devils, approaching haboobs, flash-flood dry-wash beds, and heat mirages on the horizon before they blind or swallow the convoy.", "Macro-environmental and atmospheric hazard prediction; distinct from Offroading (micro-terrain under tires) and Highway Lore (road maps)."),

    # Resilience & Biology
    ("Grit", "Physical", "Suppress physical shock, ignore shrapnel burns, and fight through cracked ribs or concussions without releasing the wheel.", "Internal physiological resilience and shock dampening; distinct from Crash Survival (bracing/tucking) and Field Dressing (treating wounds)."),
    ("Endurance", "Physical", "Endure multi-day white-line hauls, resist highway hypnosis, and stave off sleep deprivation while operating under extreme cabin heat and engine vibration.", "Sustained metabolic stamina and wakefulness over long stretches; distinct from Grit (acute trauma) and Stimulants (chemical boosters)."),
    ("Tolerance", "Physical", "Metabolize foul desert moonshine, engine-fume air, irradiated ditch swill, and raw combat chems without losing motor coordination or driving focus.", "Organic resistance to ingested toxins and industrial air; distinct from Grit (physical trauma) and Rad Cleansing (decontamination)."),
    ("Crash Survival", "Physical", "Brace limbs, tuck into cabin pockets, release the steering wheel prior to wrist-breaking kickback, and bail out cleanly during lethal wrecks.", "Minimizing fatal bodily injury during unavoidable rollover or head-on crashes; distinct from Stunt Recovery (avoiding the wreck) and Field Dressing (medical triage)."),

    # Medicine & Life Support
    ("Field Dressing", "Physical", "Pack shrapnel wounds, cauterize chemical burns, neutralize corrosive skin splashes, and set broken bones using scrap splints.", "Combat triage focused on blast and burn trauma; distinct from Poisons (identifying venom) and Chemistry (making compounds)."),
    ("Remedies", "Arcane-Mental", "Brew medicinal salves, antiseptic washes, coagulant pastes, and herbal painkillers from desert weeds, engine grease, and dried insects.", "Long-term folk pharmacology and recovery; distinct from Field Dressing (immediate triage) and Poisons (lethal venoms)."),
    ("Stimulants", "Arcane-Mental", "Distill adrenal boosters, wakefulness tonics, pain-numbing hot teas, and nerve-steadying concoctions for her crew.", "Crafting short-term combat buff consumables; distinct from Remedies (healing/restoration) and Poisons (harming foes)."),
    ("Surgery", "Arcane-Mental", "Execute sterile incisions, arterial clamps, organ repairs, and shrapnel extractions with micro-calibrated precision under moving-cabin conditions.", "Advanced surgical intervention and internal trauma repair; distinct from Triage (priority sorting) and crude Field Dressing."),
    ("Triage", "Arcane-Mental", "Scan multiple wounded crew members simultaneously to prioritize life-saving procedures based on survivability odds.", "High-pressure diagnostic decision matrices; distinct from Surgery (the operation itself) and Vitals Monitoring (tracking life signs)."),
    ("Pharmacology", "Arcane-Mental", "Calculate precise drug dosages, combat toxicity interactions, formulate coagulant injectables, and dispense synthetic anesthetics.", "Clinical synthetic biochemistry and prescription management; distinct from folk Remedies and wild Poisons."),
    ("Vitals Monitoring", "Arcane-Mental", "Track pulse, blood oxygenation, neural activity, and core body temperatures of squad mates through continuous clinical telemetry.", "Continuous passive bio-data assessment; distinct from Triage (making operational medical choices) and Surgery."),
    ("Sterilization", "Arcane-Mental", "Isolate biological contaminants, disinfect instruments, purge necrotic flesh, and scrub airborne viral spores using UV lamps and chemical rinses.", "Clinical preventative anti-pathogen protocols; distinct from environmental Rad Cleansing and caustic Acids."),
    ("Anatomy", "Arcane-Mental", "Identify vital organs, nerve junctions, arterial pathways, and skeletal weak spots on human raiders and wasteland mutants.", "Diagnostic biological map knowledge used for healing or precise lethal disabling; distinct from Surgery and Vehicle Flaws."),
    ("Bio-Waste Control", "Arcane-Mental", "Safely incinerate, seal, and neutralize infectious biohazard fluids, contaminated organs, gangrenous matter, and medical scrap.", "Safe handling of biological and pathological waste; distinct from chemical Hazard Control and Poisons."),
    ("Resuscitation", "Arcane-Mental", "Deliver rhythmic defibrillator charges, chest compressions, artificial respiration, and intracardiac epinephrine to restart stopped hearts.", "Immediate revival of clinical death and cardiac arrest; distinct from general Surgery and post-care Pharmacology."),
    ("Neural Calibration", "Arcane-Mental", "Administer neuro-stimulators, electro-convulsive shocks, and cognitive focusing routines to cure concussions, flashbang blindness, and panic paralysis.", "Treating brain trauma, shock, and sensory overload; distinct from chemical Pharmacology and physical Resuscitation."),
    ("Forensics", "Arcane-Mental", "Scan bullet trajectories, tissue lacerations, chemical residues, and tire tracks to reconstruct crime scenes, ambushes, or cause of death.", "Post-incident investigative crime and death analysis; distinct from live-combat Target Profiling and Scavenging."),

    # Social & Influence
    ("Deception", "Social", "Project false frailty, harmless doting, or mock subservience to lower enemy guards, stall executions, or distract hostiles.", "Social camouflage weaponizing perceived weakness and harmlessness; distinct from Concealment (hiding items) and Intimidation."),
    ("Intimidation", "Social", "Project silent, menacing physical presence, dead-eyed glares, and roaring throttle revs to bully smaller cars out of lanes and terrify raiders.", "Aggressive social dominance through size and machinery; distinct from deceptive social tricks like Deception or negotiation."),
    ("Raider Lore", "Social", "Anticipate marauder swarm tactics, intercept vectors, boarding patterns, and tribal pack hierarchies from past wasteland experience.", "Tactical and psychological understanding of enemy behavior to predict ambushes; distinct from mechanical or chemical crafting."),
    ("Sign Language", "Social", "Convey tactical alerts, mechanical statuses, emotions, and enemy locations through rapid, silent hand signs and visual codes.", "Non-verbal tactical and covert communication; distinct from verbal speech and Deception."),
    ("Acoustic Mimicry", "Social", "Imitate hydraulic hisses, siren chirps, metallic groans, radio tones, or beast calls to confuse pursuers, transmit signals, or lure hostiles.", "Auditory vocal misdirection and acoustic signaling; distinct from visual Sign Language and Deception.")
]

dst_path = r"C:\Users\Thiago\Desktop\Skills.csv"
with open(dst_path, mode="w", newline="", encoding="utf-8") as f:
    writer = csv.writer(f)
    writer.writerow(["Skill Name", "Category", "Internal Verb Definition", "Overlaps / Distinctions"])
    for row in data:
        writer.writerow(row)

print(f"Successfully wrote {len(data)} unique skills to {dst_path}")
